Repository tukcom2023CD/DragonGuard-JinJin, pull requests merged in 2023-02, with the labels that each got.

#35 [#10] ios 검색 기능 개발 완료
  ios/ios.xcodeproj/project.pbxproj
  ios/ios/APIURL.swift
  ios/ios/Model/SearchPageDecodingModel.swift
  ios/ios/Model/SearchPageResultModel.swift
  ios/ios/Services/SearchPageService.swift
  ios/ios/View/MainController.swift
  ios/ios/View/SearchPageController.swift
  ios/ios/View/SearchPageTableView.swift
  ios/ios/ViewModel/SearchPageViewModel.swift
Labels: feature

#36 repository commits contributors scrapping 기능
  backend/src/main/java/com/dragonguard/backend/commit/messagequeue/KafkaCommitConsumer.java
  backend/src/main/java/com/dragonguard/backend/member/dto/request/MemberRequest.java
  backend/src/main/java/com/dragonguard/backend/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Member.java
  backend/src/main/java/com/dragonguard/backend/member/mapper/MemberMapper.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/main/resources/application-dev.yml
  docker-compose.yml
  scrapping/Dockerfile
  scrapping/app.py
  scrapping/base_url.py
  scrapping/requirements.txt
Labels: feature

#40 [#39] docker mac error 해결
  .gitignore
  backend/src/main/java/com/dragonguard/backend/commit/service/CommitService.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/entity/GitRepoMember.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/service/GitRepoMemberService.java
  docker-compose.yml
  scrapping/Dockerfile
  scrapping/app.py
  scrapping/firefox_config.py
  scrapping/kafka_config.py
Labels: bug

#42 [#41] documetation
  backend/src/docs/asciidoc/gitrepo.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/test/java/com/dragonguard/backend/gitrepo/controller/GitRepoControllerTest.java
  backend/src/test/java/com/dragonguard/backend/member/controller/MemberControllerTest.java
  backend/src/test/java/com/dragonguard/backend/support/fixture/member/dto/MemberRequestFixture.java
  scrapping/app.py
Labels: documentation

#44 [#43] rename scrap to scrape
  README.md
  backend/src/main/java/com/dragonguard/backend/commit/client/CommitClient.java
  backend/src/main/java/com/dragonguard/backend/commit/dto/request/CommitScrapingRequest.java
  backend/src/main/java/com/dragonguard/backend/commit/dto/response/CommitScrapingResponse.java
  backend/src/main/java/com/dragonguard/backend/commit/mapper/CommitMapper.java
  backend/src/main/java/com/dragonguard/backend/commit/messagequeue/KafkaCommitConsumer.java
  backend/src/main/java/com/dragonguard/backend/commit/service/CommitService.java
  backend/src/main/java/com/dragonguard/backend/config/kafka/KafkaConfig.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/client/GitRepoClient.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  backend/src/main/java/com/dragonguard/backend/global/exception/ScrapingRequestFailException.java
  backend/src/main/java/com/dragonguard/backend/global/webclient/ScrapingClient.java
  backend/src/main/java/com/dragonguard/backend/global/webclient/ScrappingClient.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/main/java/com/dragonguard/backend/search/client/SearchClient.java
  backend/src/main/java/com/dragonguard/backend/search/service/SearchService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  docker-compose.yml
  nginx/nginx.conf
  scraping/Dockerfile
  scraping/app.py
  scraping/config/base_url.py
  scraping/config/firefox_config.py
  scraping/config/kafka_config.py
  scraping/config/swagger_config.py
  scraping/requirements.txt
  scraping/wait-for-it.sh
Labels: refactoring

#46 [#45] 멤버 개별 조회시 랭크 동시 조회
  backend/src/main/java/com/dragonguard/backend/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dragonguard/backend/member/mapper/MemberMapper.java
  backend/src/main/java/com/dragonguard/backend/member/repository/MemberQueryRepository.java
  backend/src/main/java/com/dragonguard/backend/member/repository/MemberQueryRepositoryImpl.java
  backend/src/main/java/com/dragonguard/backend/member/repository/MemberRepository.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/test/java/com/dragonguard/backend/member/controller/MemberControllerTest.java
Labels: feature

#47 Feat/#32 android main screen
  .gitignore
  android/.gradle/7.2/fileHashes/fileHashes.bin
  android/.gradle/7.2/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  android/.idea/workspace.xml
  android/app/src/main/java/com/dragonguard/android/activity/MainActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/RepoContributorsActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/SearchActivity.kt
  android/app/src/main/java/com/dragonguard/android/connect/ApiRepository.kt
  android/app/src/main/java/com/dragonguard/android/model/UserInfoModel.kt
  android/app/src/main/java/com/dragonguard/android/recycleradapter/ContributorsAdapter.kt
  android/app/src/main/res/layout/activity_repo_contributors.xml
Labels: feature

#48 [#30] add chmod Docker-file
  scraping/Dockerfile
  scraping/wait-for-it.sh
Labels: feature

#49 [#30] Repository Contributor 정보 및 차트 기능
  ios/ios/APIURL.swift
  ios/ios/Services/RepoContributorInfoService.swift
  ios/ios/View/RepoContributorInfoController.swift
  ios/ios/ViewModel/RepoContributorInfoViewModel.swift
Labels: feature

#53 [#52] kafka 호출 구조 수정
  .gitignore
  backend/src/main/java/com/dragonguard/backend/commit/client/CommitClient.java
  backend/src/main/java/com/dragonguard/backend/commit/dto/request/CommitScrapingRequest.java
  backend/src/main/java/com/dragonguard/backend/commit/messagequeue/KafkaCommitProducer.java
  backend/src/main/java/com/dragonguard/backend/commit/service/CommitService.java
  backend/src/main/java/com/dragonguard/backend/config/converter/ConverterConfig.java
  backend/src/main/java/com/dragonguard/backend/config/kafka/KafkaConsumerConfig.java
  backend/src/main/java/com/dragonguard/backend/config/kafka/KafkaProducerConfig.java
  backend/src/main/java/com/dragonguard/backend/config/kafka/KafkaTopicConfig.java
  backend/src/main/java/com/dragonguard/backend/config/redis/CacheKey.java
  backend/src/main/java/com/dragonguard/backend/config/redis/RedisConfig.java
  backend/src/main/java/com/dragonguard/backend/config/redis/RedisProperties.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/client/GitRepoClient.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/messagequeue/KafkaGitRepoConsumer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/messagequeue/KafkaGitRepoProducer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/entity/GitRepoMember.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/repository/GitRepoMemberRepository.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/service/GitRepoMemberService.java
  backend/src/main/java/com/dragonguard/backend/global/kafka/KafkaProducer.java
  backend/src/main/java/com/dragonguard/backend/global/webclient/ScrapingClient.java
  backend/src/main/java/com/dragonguard/backend/result/entity/Result.java
  backend/src/main/java/com/dragonguard/backend/result/messagequeue/KafkaResultConsumer.java
  backend/src/main/java/com/dragonguard/backend/result/repository/ResultRepository.java
  backend/src/main/java/com/dragonguard/backend/search/client/SearchClient.java
  backend/src/main/java/com/dragonguard/backend/search/controller/SearchController.java
  backend/src/main/java/com/dragonguard/backend/search/converter/SearchTypeConverter.java
  backend/src/main/java/com/dragonguard/backend/search/dto/request/KafkaSearchRequest.java
  backend/src/main/java/com/dragonguard/backend/search/dto/request/SearchRequest.java
  backend/src/main/java/com/dragonguard/backend/search/entity/Search.java
  backend/src/main/java/com/dragonguard/backend/search/entity/SearchType.java
  backend/src/main/java/com/dragonguard/backend/search/messagequeue/KafkaSearchProducer.java
  backend/src/main/java/com/dragonguard/backend/search/repository/SearchRepository.java
  backend/src/main/java/com/dragonguard/backend/search/service/SearchService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  docker-compose.yml
  nginx/nginx.conf
  scraping/Dockerfile
  scraping/app.py
  scraping/config/base_url.py
  scraping/config/kafka_config.py
  scraping/config/swagger_config.py
  scraping/requirements.txt
Labels: feature, refactoring

#54 Feat/#32 android main screen
  android/app/src/main/java/com/dragonguard/android/activity/MainActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/RepoContributorsActivity.kt
Labels: feature

#56 [#55] apply elk by docker
  .gitattributes
  docker-compose.logging.yml
  docker-compose.yml
  elk/elasticsearch/.dockerignore
  elk/elasticsearch/Dockerfile
  elk/elasticsearch/config/elasticsearch.yml
  elk/filebeat/.dockerignore
  elk/filebeat/Dockerfile
  elk/filebeat/config/filebeat.yml
  elk/kibana/.dockerignore
  elk/kibana/Dockerfile
  elk/kibana/config/kibana.yml
  elk/logstash/.dockerignore
  elk/logstash/Dockerfile
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/logstash.conf
Labels: settings, feature

#57 [#30] iOS main screen
  ios/ios.xcodeproj/project.pbxproj
  ios/ios/APIURL.swift
  ios/ios/Delegate/AppDelegate.swift
  ios/ios/Model/MainModel.swift
  ios/ios/Services/MainService.swift
  ios/ios/Services/UserInfoService.swift
  ios/ios/View/MainController.swift
  ios/ios/View/MainScreen/WatchRankingCollectionView.swift
  ios/ios/View/MainScreen/WatchRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/AllRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/AllRepositoryRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/AllUnivRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/MyOrganizationListController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/MyRepositoryRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/UnivInRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/WatchRankingTableView.swift
  ios/ios/View/TierTokenCustomUIView.swift
  ios/ios/ViewModel/MainViewModel.swift
  ios/ios/ViewModel/RepoContributorInfoViewModel.swift
Labels: feature

#60 [#59] use github api in repo contributor api
  backend/src/main/java/com/dragonguard/backend/gitrepo/client/GitRepoClient.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/controller/GitRepoController.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/messagequeue/KafkaGitRepoConsumer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/response/Author.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/response/GitRepoClientResponse.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/response/GitRepoMemberClientResponse.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/response/GitRepoMemberResponse.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/response/Week.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/mapper/GitRepoMemberMapper.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/service/GitRepoMemberService.java
  backend/src/main/java/com/dragonguard/backend/global/exception/BusinessException.java
  backend/src/main/java/com/dragonguard/backend/global/exception/EntityNotFoundException.java
  backend/src/main/java/com/dragonguard/backend/global/exception/ScrapingRequestFailException.java
  backend/src/main/java/com/dragonguard/backend/global/exception/WebClientException.java
  backend/src/main/java/com/dragonguard/backend/global/webclient/GithubClient.java
  backend/src/main/java/com/dragonguard/backend/member/entity/CommitDuplicateException.java
  backend/src/main/java/com/dragonguard/backend/member/entity/TierNoneMatchException.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/dragonguard/backend/gitrepo/controller/GitRepoControllerTest.java
Labels: feature, fix

#62 [#30] iOS 전체 사용자 랭킹, 대학교 내 랭킹
  ios/ios.xcodeproj/project.pbxproj
  ios/ios/APIURL.swift
  ios/ios/Delegate/AppDelegate.swift
  ios/ios/Model/MainModel.swift
  ios/ios/Model/RepoContributorInfoModel.swift
  ios/ios/Model/SearchPageResultModel.swift
  ios/ios/Services/MainService.swift
  ios/ios/Services/PostService.swift
  ios/ios/Services/SearchPageService.swift
  ios/ios/Services/UserInfoService.swift
  ios/ios/View/MainCollectionView.swift
  ios/ios/View/MainController.swift
  ios/ios/View/MainRankingCollectionView.swift
  ios/ios/View/MainScreen/CompareRepositorycontroller.swift
  ios/ios/View/MainScreen/WatchRankingCollectionView.swift
  ios/ios/View/MainScreen/WatchRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/AllRankingController.swift
  ios/ios/View/RepoContributorInfoController.swift
  ios/ios/View/RepoContributorTableView.swift
  ios/ios/View/SearchPageController.swift
  ios/ios/View/TierTokenCustomUIView.swift
  ios/ios/ViewModel/MainViewModel.swift
  ios/ios/ViewModel/RepoContributorInfoViewModel.swift
Labels: feature

#66 [#64] backend klaytn 연동 완료
  .gitignore
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/dragonguard/backend/blockchain/controller/BlockchainController.java
  backend/src/main/java/com/dragonguard/backend/blockchain/dto/request/BlockchainRequest.java
  backend/src/main/java/com/dragonguard/backend/blockchain/dto/request/ContractRequest.java
  backend/src/main/java/com/dragonguard/backend/blockchain/dto/response/BlockchainResponse.java
  backend/src/main/java/com/dragonguard/backend/blockchain/entity/Blockchain.java
  backend/src/main/java/com/dragonguard/backend/blockchain/entity/ContributeType.java
  backend/src/main/java/com/dragonguard/backend/blockchain/mapper/BlockchainMapper.java
  backend/src/main/java/com/dragonguard/backend/blockchain/repository/BlockchainRepository.java
  backend/src/main/java/com/dragonguard/backend/blockchain/service/BlockchainService.java
  backend/src/main/java/com/dragonguard/backend/blockchain/service/TransactionService.java
  backend/src/main/java/com/dragonguard/backend/config/blockchain/BlockchainConfig.java
  backend/src/main/java/com/dragonguard/backend/config/blockchain/BlockchainProperties.java
  backend/src/main/java/com/dragonguard/backend/config/blockchain/BlockchainString.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/client/GitRepoClient.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/service/GitRepoMemberService.java
  backend/src/main/java/com/dragonguard/backend/global/exception/BlockchainException.java
  backend/src/main/java/com/dragonguard/backend/member/controller/MemberController.java
  backend/src/main/java/com/dragonguard/backend/member/dto/request/WalletRequest.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Member.java
  backend/src/main/java/com/dragonguard/backend/member/repository/MemberRepository.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/main/java/com/dragonguard/backend/search/client/SearchRepoClient.java
  backend/src/main/java/com/dragonguard/backend/search/client/SearchUserClient.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
Labels: feature

#68 [#67] backend compare api
  backend/src/main/java/com/dragonguard/backend/blockchain/entity/Blockchain.java
  backend/src/main/java/com/dragonguard/backend/commit/entity/Commit.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/controller/GitRepoController.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/dto/request/GitRepoCompareRequest.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/entity/GitRepo.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/mapper/GitRepoMapper.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/request/GitRepoMemberCompareRequest.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/dto/response/TwoGitRepoMemberResponse.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/entity/GitRepoMember.java
  backend/src/main/java/com/dragonguard/backend/gitrepomember/repository/GitRepoMemberRepository.java
  backend/src/main/java/com/dragonguard/backend/global/SoftDelete.java
  backend/src/main/java/com/dragonguard/backend/issue/entity/Issue.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Member.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Tier.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/main/java/com/dragonguard/backend/university/entity/University.java
  backend/src/test/java/com/dragonguard/backend/gitrepo/controller/GitRepoControllerTest.java
Labels: feature

#69 [#67] compare api
  backend/src/main/java/com/dragonguard/backend/config/kafka/KafkaTopicConfig.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/dto/request/GitRepoNameRequest.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/dto/response/GitRepoClientResponse.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/entity/GitRepo.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/messagequeue/KafkaGitRepoConsumer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/messagequeue/KafkaIssueConsumer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/messagequeue/KafkaIssueProducer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  scraping/app.py
Labels: feature

#73 [#72] change not to return min and max value
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
Labels: fix

#74 Feat/#63 android apply token
  android/app/src/main/java/com/dragonguard/android/activity/RepoCompareActivity.kt
  android/app/src/main/java/com/dragonguard/android/connect/ApiRepository.kt
  android/app/src/main/java/com/dragonguard/android/fragment/CompareRepoFragment.kt
  android/app/src/main/java/com/dragonguard/android/fragment/CompareUserFragment.kt
  android/app/src/main/java/com/dragonguard/android/recycleradapter/RepoCompareChartAdapter.kt
  android/app/src/main/res/layout/fragment_compare_repo.xml
  android/app/src/main/res/layout/repo_compare_chart.xml
Labels: feature
