Repository tukcom2023CD/DragonGuard-JinJin, pull requests merged in 2023-01, with the labels that each got.

#4 [#2] db 및 backend docker 설정
  .gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: feature, Asking for Review

#8 [#7] Backend 초기 클래스 작성
  backend/src/main/java/com/dragonguard/backend/blockchain/controller/BlockchainController.java
  backend/src/main/java/com/dragonguard/backend/blockchain/dto/request/BlockchainRequest.java
  backend/src/main/java/com/dragonguard/backend/blockchain/dto/response/BlockchainResponse.java
  backend/src/main/java/com/dragonguard/backend/blockchain/entity/Blockchain.java
  backend/src/main/java/com/dragonguard/backend/blockchain/mapper/BlockchainMapper.java
  backend/src/main/java/com/dragonguard/backend/blockchain/repository/BlockchainRepository.java
  backend/src/main/java/com/dragonguard/backend/blockchain/service/BlockchainService.java
  backend/src/main/java/com/dragonguard/backend/commit/controller/CommitController.java
  backend/src/main/java/com/dragonguard/backend/commit/dto/request/CommitRequest.java
  backend/src/main/java/com/dragonguard/backend/commit/dto/response/CommitResponse.java
  backend/src/main/java/com/dragonguard/backend/commit/entity/Commit.java
  backend/src/main/java/com/dragonguard/backend/commit/mapper/CommitMapper.java
  backend/src/main/java/com/dragonguard/backend/commit/repository/CommitRepository.java
  backend/src/main/java/com/dragonguard/backend/commit/service/CommitService.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/controller/GitRepoController.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/dto/request/GitRepoRequest.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/dto/response/GitRepoResponse.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/entity/GitRepo.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/mapper/GitRepoMapper.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/repository/GitRepoRepository.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/service/GitRepoService.java
  backend/src/main/java/com/dragonguard/backend/global/BaseTime.java
  backend/src/main/java/com/dragonguard/backend/issue/controller/IssueController.java
  backend/src/main/java/com/dragonguard/backend/issue/dto/request/IssueRequest.java
  backend/src/main/java/com/dragonguard/backend/issue/dto/response/IssueResponse.java
  backend/src/main/java/com/dragonguard/backend/issue/entity/Issue.java
  backend/src/main/java/com/dragonguard/backend/issue/mapper/IssueMapper.java
  backend/src/main/java/com/dragonguard/backend/issue/repository/IssueRepository.java
  backend/src/main/java/com/dragonguard/backend/issue/service/IssueService.java
  backend/src/main/java/com/dragonguard/backend/member/controller/MemberController.java
  backend/src/main/java/com/dragonguard/backend/member/dto/request/MemberRequest.java
  backend/src/main/java/com/dragonguard/backend/member/dto/response/MemberResponse.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Member.java
  backend/src/main/java/com/dragonguard/backend/member/mapper/MemberMapper.java
  backend/src/main/java/com/dragonguard/backend/member/repository/MemberRepository.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/main/java/com/dragonguard/backend/university/controller/UniversityController.java
  backend/src/main/java/com/dragonguard/backend/university/dto/request/UniversityRequest.java
  backend/src/main/java/com/dragonguard/backend/university/dto/response/UniversityResponse.java
  backend/src/main/java/com/dragonguard/backend/university/entity/University.java
  backend/src/main/java/com/dragonguard/backend/university/mapper/UniversityMapper.java
  backend/src/main/java/com/dragonguard/backend/university/repository/UniversityRepository.java
  backend/src/main/java/com/dragonguard/backend/university/service/UniversityService.java
Labels: settings, feature

#13 repository명 및 user명 목록 scrapping api
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
  scrapping/Dockerfile
  scrapping/app.py
  scrapping/requirements.txt
Labels: feature

#18 Feat/#11 android search page
  android/.gradle/7.2/fileHashes/fileHashes.bin
  android/.gradle/7.2/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  android/.idea/misc.xml
  android/.idea/workspace.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/dragonguard/android/MainActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/LoadingActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/LoginActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/MainActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/SearchActivity.kt
  android/app/src/main/java/com/dragonguard/android/model/SearchModel.kt
  android/app/src/main/java/com/dragonguard/android/recycleradapter/HorizontalItemDecorator.kt
  android/app/src/main/java/com/dragonguard/android/recycleradapter/RepositoryProfileAdapter.kt
  android/app/src/main/java/com/dragonguard/android/recycleradapter/VerticalItemDecorator.kt
  android/app/src/main/java/com/dragonguard/android/viewmodel/SearchViewModel.kt
  android/app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  android/app/src/main/res/drawable/ic_baseline_arrow_drop_up_24.xml
  android/app/src/main/res/drawable/ic_baseline_search_24.xml
  android/app/src/main/res/drawable/search_border.xml
  android/app/src/main/res/layout/activity_loading.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_search.xml
  android/app/src/main/res/layout/repository_list.xml
Labels: feature

#19 [#16] 멤버 커밋수 스크래핑 api
  .gitignore
  scrapping/app.py
Labels: feature

#22 Feat/#10 search page
  ios/ios.xcodeproj/project.pbxproj
  ios/ios/View/SearchPageController.swift
  ios/ios/View/SearchPageTableView.swift
  ios/ios/ViewModel/testViewModel.swift
Labels: bug, feature, In Progress

#24 Feat/#11 android search page
  android/.gradle/7.2/fileHashes/fileHashes.bin
  android/.gradle/7.2/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  android/.idea/workspace.xml
  android/app/src/main/java/com/dragonguard/android/activity/SearchActivity.kt
  android/app/src/main/java/com/dragonguard/android/connect/ApiCall.kt
  android/app/src/main/java/com/dragonguard/android/connect/GitRankAPI.kt
  android/local.properties
Labels: feature

#29 [#28] github actions 파일 확장자 적용
  .github/workflows/android_dev.yml
  .github/workflows/backend_dev.yml
  .github/workflows/ios_dev.yml
Labels: feature

#33 [#31] api 목록 rest docs를 통한 문서화
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/search.adoc
  backend/src/main/java/com/dragonguard/backend/commit/entity/Commit.java
  backend/src/main/java/com/dragonguard/backend/commit/messagequeue/KafkaCommitConsumer.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/entity/GitRepo.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Tier.java
  backend/src/main/java/com/dragonguard/backend/result/messagequeue/KafkaResultConsumer.java
  backend/src/test/java/com/dragonguard/backend/BackendApplicationTests.java
  backend/src/test/java/com/dragonguard/backend/member/controller/MemberControllerTest.java
  backend/src/test/java/com/dragonguard/backend/search/controller/SearchControllerTest.java
  backend/src/test/java/com/dragonguard/backend/support/docs/ApiDocumentUtils.java
  backend/src/test/java/com/dragonguard/backend/support/docs/RestDocsConfiguration.java
  backend/src/test/java/com/dragonguard/backend/support/docs/RestDocumentTest.java
  backend/src/test/java/com/dragonguard/backend/support/fixture/member/dto/MemberRequestFixture.java
Labels: documentation
