Repository tukcom2023CD/DragonGuard-JinJin, pull requests merged in 2023-03, with the labels that each got.

#75 [#65] ios apply token
  ios/ios.xcodeproj/project.pbxproj
  ios/ios/APIURL.swift
  ios/ios/Delegate/AppDelegate.swift
  ios/ios/Model/CompareRepoModel.swift
  ios/ios/Model/CompareUserModel.swift
  ios/ios/Model/UserInfoModel.swift
  ios/ios/Notification.swift
  ios/ios/Services/CompareService.swift
  ios/ios/Services/KlipLoginService.swift
  ios/ios/Services/MainService.swift
  ios/ios/Services/PostService.swift
  ios/ios/Services/RepoContributorInfoService.swift
  ios/ios/Services/UserInfoService.swift
  ios/ios/View/KlipLoginCheckview.swift
  ios/ios/View/KlipLoginController.swift
  ios/ios/View/MainScreen/CompareGraphController.swift
  ios/ios/View/MainScreen/CompareRepoCollectionView.swift
  ios/ios/View/MainScreen/CompareRepoTableView.swift
  ios/ios/View/MainScreen/CompareRepositorycontroller.swift
  ios/ios/View/MainScreen/CompareSelectedUserTableView.swift
  ios/ios/View/MainScreen/CompareSelectedUserView.swift
  ios/ios/View/MainScreen/CompareUserController.swift
  ios/ios/View/MainScreen/TabBarController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/AllRankingController.swift
  ios/ios/View/MainScreen/WatchRankingScreen/AllRepositoryRankingCollectionView.swift
  ios/ios/View/RepoContributorInfoController.swift
  ios/ios/View/RepoContributorTableView.swift
  ios/ios/View/SearchPageController.swift
  ios/ios/View/TierTokenCustomUIView.swift
  ios/ios/ViewModel/CompareViewModel.swift
  ios/ios/ViewModel/KlipLoginViewModel.swift
  ios/ios/ViewModel/LoginViewModel.swift
  ios/ios/ViewModel/RepoContributorInfoViewModel.swift
  ios/ios/ViewModel/UserInfoViewModel.swift
Labels: feature

#82 [#80] filter search api
  backend/src/docs/asciidoc/search.adoc
  backend/src/main/java/com/dragonguard/backend/BackendApplication.java
  backend/src/main/java/com/dragonguard/backend/config/redis/RedisConfig.java
  backend/src/main/java/com/dragonguard/backend/global/BaseTime.java
  backend/src/main/java/com/dragonguard/backend/result/dto/response/ResultResponse.java
  backend/src/main/java/com/dragonguard/backend/result/entity/Result.java
  backend/src/main/java/com/dragonguard/backend/result/mapper/ResultMapper.java
  backend/src/main/java/com/dragonguard/backend/result/repository/ResultRepository.java
  backend/src/main/java/com/dragonguard/backend/search/client/SearchRepoClient.java
  backend/src/main/java/com/dragonguard/backend/search/client/SearchUserClient.java
  backend/src/main/java/com/dragonguard/backend/search/controller/SearchController.java
  backend/src/main/java/com/dragonguard/backend/search/dto/request/SearchRequest.java
  backend/src/main/java/com/dragonguard/backend/search/entity/Filter.java
  backend/src/main/java/com/dragonguard/backend/search/entity/Search.java
  backend/src/main/java/com/dragonguard/backend/search/mapper/SearchMapper.java
  backend/src/main/java/com/dragonguard/backend/search/repository/SearchRepository.java
  backend/src/main/java/com/dragonguard/backend/search/service/SearchService.java
  backend/src/test/java/com/dragonguard/backend/search/controller/SearchControllerTest.java
Labels: documentation, feature

#86 [#78] ios filtering
  .gitignore
  ios/ios.xcodeproj/project.pbxproj
  ios/ios/APIURL.swift
  ios/ios/Assets.xcassets/img1.imageset/Contents.json
  ios/ios/Assets.xcassets/img1.imageset/SNOW_20221001_113715_379 1.jpg
  ios/ios/Assets.xcassets/img1.imageset/SNOW_20221001_113715_379 2.jpg
  ios/ios/Assets.xcassets/img1.imageset/SNOW_20221001_113715_379.jpg
  ios/ios/Model/UserDBIdModel.swift
  ios/ios/Notification.swift
  ios/ios/Services/PostService.swift
  ios/ios/Services/SearchPageService.swift
  ios/ios/View/MainScreen/MainController.swift
  ios/ios/View/SearchController/Filltering/FilteringController.swift
  ios/ios/View/SearchController/Filltering/ForkSelectionCollectionViewCell.swift
  ios/ios/View/SearchController/Filltering/LanguageFiltering/LanguageFillteringTableView.swift
  ios/ios/View/SearchController/Filltering/LanguageFiltering/LanguageFillteringTableViewCell.swift
  ios/ios/View/SearchController/Filltering/LanguageSelectionsCollectionViewCell.swift
  ios/ios/View/SearchController/Filltering/StarSelectionCollectionViewCell.swift
  ios/ios/View/SearchController/Filltering/TopicSelectionCollectionViewCell.swift
  ios/ios/View/SearchController/Filltering/TypeCollectionViewCell.swift
  ios/ios/View/SearchController/FilteringCollectionViewCell.swift
  ios/ios/View/SearchController/SearchPageController.swift
  ios/ios/ViewModel/SearchPageViewModel.swift
Labels: feature

#92 [#89] Email 조직 인증
  backend/build.gradle
  backend/src/main/java/com/dragonguard/backend/email/controller/EmailController.java
  backend/src/main/java/com/dragonguard/backend/email/dto/request/EmailRequest.java
  backend/src/main/java/com/dragonguard/backend/email/dto/response/CheckCodeResponse.java
  backend/src/main/java/com/dragonguard/backend/email/entity/Email.java
  backend/src/main/java/com/dragonguard/backend/email/exception/EmailException.java
  backend/src/main/java/com/dragonguard/backend/email/repository/EmailRepository.java
  backend/src/main/java/com/dragonguard/backend/email/service/EmailService.java
  backend/src/main/java/com/dragonguard/backend/gitrepo/entity/GitRepo.java
  backend/src/main/java/com/dragonguard/backend/member/controller/MemberController.java
  backend/src/main/java/com/dragonguard/backend/member/entity/Member.java
  backend/src/main/java/com/dragonguard/backend/member/service/MemberService.java
  backend/src/main/java/com/dragonguard/backend/organization/dto/request/AddMemberRequest.java
  backend/src/main/java/com/dragonguard/backend/organization/entity/Organization.java
  backend/src/main/java/com/dragonguard/backend/organization/service/OrganizationService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
Labels: feature

#93 [#88] android auto login logout
  android/app/src/main/java/com/dragonguard/android/activity/LoginActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/MainActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/compare/RepoCompareActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/menu/CriterionActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/menu/FaqActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/menu/MenuActivity.kt
  android/app/src/main/java/com/dragonguard/android/activity/search/RepoContributorsActivity.kt
  android/app/src/main/java/com/dragonguard/android/connect/ApiRepository.kt
  android/app/src/main/java/com/dragonguard/android/connect/GitRankAPI.kt
  android/app/src/main/java/com/dragonguard/android/model/FaqModel.kt
  android/app/src/main/java/com/dragonguard/android/preferences/IdPreference.kt
  android/app/src/main/java/com/dragonguard/android/recycleradapter/FaqAdapter.kt
  android/app/src/main/res/drawable/baseline_arrow_right_24.xml
  android/app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  android/app/src/main/res/drawable/ic_baseline_arrow_drop_up_24.xml
  android/app/src/main/res/drawable/round_pink.xml
  android/app/src/main/res/drawable/round_title.xml
  android/app/src/main/res/layout/activity_criterion.xml
  android/app/src/main/res/layout/activity_faq.xml
  android/app/src/main/res/layout/faq_list.xml
  android/app/src/main/res/layout/version_dialog.xml
Labels: feature

#95 [#94] test code error and update api docs
  backend/build.gradle
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/email.adoc
  backend/src/docs/asciidoc/gitrepo.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/organization.adoc
  backend/src/main/java/com/dragonguard/backend/email/service/EmailService.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/dragonguard/backend/BackendApplicationTests.java
  backend/src/test/java/com/dragonguard/backend/blockchain/controller/BlockchainControllerTest.java
  backend/src/test/java/com/dragonguard/backend/email/controller/EmailControllerTest.java
  backend/src/test/java/com/dragonguard/backend/gitrepo/controller/GitRepoControllerTest.java
  backend/src/test/java/com/dragonguard/backend/member/controller/AuthControllerTest.java
  backend/src/test/java/com/dragonguard/backend/member/controller/MemberControllerTest.java
  backend/src/test/java/com/dragonguard/backend/organization/controller/OrganizationControllerTest.java
  backend/src/test/java/com/dragonguard/backend/search/controller/SearchControllerTest.java
  backend/src/test/java/com/dragonguard/backend/support/config/TestRedisConfiguration.java
  backend/src/test/java/com/dragonguard/backend/support/database/DatabaseTest.java
  backend/src/test/java/com/dragonguard/backend/support/database/LoginTest.java
  backend/src/test/java/com/dragonguard/backend/support/docs/RestDocumentTest.java
Labels: documentation, fix
